### ISSUE TITLE
Typos Errors Relationships Page 2

### ISSUE THREAD

**Issue by jmseck** [robgungor/healthyliving#4]
Yes
"I'm going to hang with my old friend, I miss them so much."
No
"I want to develop new these new friends. I always fell so homesick. seeing my old friends."

Relationships 2nd page - Typos/errors? 

I want to develop new these new friends. ( I want to develop these new friends)
I always fell (feel) so homesick. (no period) seeing my old friends.

**Comment by eternitybro** [comment]
fixed, please verify
