### ISSUE TITLE
Navigation Question

### ISSUE THREAD

**Issue by jmseck** [robgungor/healthyliving#5]
Clicking Good Job takes you back to Main Menu.  Is this the appropriate functionality?
Should it not take you back to the other options in that category?

Should 'Go Back' button be repositioned to have the same significance as good job or should good job just take you back one menu level rather than return you to the Main Menu until all items have been viewed/completed?

**Comment by eternitybro** [comment]
I could do that.. I was thinking that the default action would be to keep the user moving forward... "HOME" might not be easily understood. Simone, what do you think?

**Comment by jmseck** [comment]
I think moving forward is a good idea, but shouldn't we be encouraging users to view all the content?
How is the overall score working given the current setup?

If you just view one item out of say 5 potential choices, is this considered a completed section?

**Comment by eternitybro** [comment]
Right now the score is only determined by whether they hit yes or no on the scenario page - but that tally doesn't happen until they click "good job" and go back home. If they click yes it adds 17% to the score, if they click no it adds 10% - so if they click the wrong answer for every scenario they will get an F. I tried to make the scoring similar to a grading system.

**Comment by jmseck** [comment]
So it's not related to how much of the content they view overall?

**Comment by eternitybro** [comment]
No it is not. I don't think that makes sense as a user.. You're judged on your choices... Not what you did and didn't read.
But if you want to do something like that we can... But how do the scenarios then work into the score?

**Comment by jmseck** [comment]
Ok, let's leave it as.

**Comment by simonerubi** [comment]
I'm just seeing this now... Yes, I think leave as is
