### ISSUE TITLE
100% score color 

### ISSUE THREAD

**Issue by jmseck** [robgungor/healthyliving#6]
Hi, 

Just wondering. Do you guys think this is an appropriate color for the final screen. A+ Congratulations, you're done. Black? Wondering if green might be more appropriate/positive. Not a necessity, just a question.

John

![screen shot 2015-05-03 at 1 18 12 pm](https://cloud.githubusercontent.com/assets/8633992/7446025/046aec16-f198-11e4-95ee-dcee261dcb45.png)

**Comment by jmseck** [comment]
Also Algonquin might like their green as the final/positive result.

**Comment by eternitybro** [comment]
Sure we can do that. Do you want colors for each result? Or just green for 100%...

**Comment by jmseck** [comment]
I think green for the 100% and maybe you could choose a couple of other colors for the other results or just one, up to you.  Just want to be sure to have a positive feeling for users at the end.

**Comment by eternitybro** [comment]
Totally. Do we also want to use red/yellow for when they score poorly? As an incentive to try again...

**Comment by jmseck** [comment]
Yes, I think that would be ideal. As long as we stay within the Algonquin color palette,.

**Comment by jmseck** [comment]
Thinking about this again. Could we stay away from red and maybe use an orange if that's in the palette?
Just want to avoid the discouraging red as a 'Stop'.  If it's not too much trouble.
